# Generated by Django 3.2.4 on 2021-08-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'مقدار'), ('P', 'درصدی')], default='C', max_length=5)),
                ('percent_discount', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف درصدی')),
                ('cash_discount', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف نقدی')),
                ('code_discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف')),
                ('validate_date', models.DateTimeField(verbose_name='تاریخ اعمال کد تخفیف')),
                ('expire_date', models.DateTimeField(verbose_name='تاریخ اعتبار کد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف کددار',
                'verbose_name_plural': 'تخفیف های کددار',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد سفارش')),
                ('total_price', models.IntegerField(verbose_name='قیمت کل')),
                ('complete', models.BooleanField(default=False, verbose_name='تکمیل خرید')),
                ('total_discount', models.IntegerField(verbose_name='تخفیف کل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('discount_code', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.basketdiscount', verbose_name='تخفیف کدی')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش های  کاربران',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'مقدار'), ('P', 'درصدی')], default='C', max_length=4)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='نام تخفیف نقدی')),
                ('cash_discount', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف نقدی')),
                ('percent_discount', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف درصدی')),
                ('max_purchase', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='سقف خرید')),
                ('validate_date', models.DateTimeField(verbose_name='تاریخ اعمال تخفیف')),
                ('expire_date', models.DateTimeField(verbose_name='تاریخ اعتبار تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت تخفیف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.book')),
            ],
            options={
                'verbose_name': 'تخفیف نقدی',
                'verbose_name_plural': 'تخفیف های نقدی',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.book', verbose_name='محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'ایتم سفارش',
                'verbose_name_plural': 'ایتم های سفارش',
            },
        ),
    ]
