# Generated by Django 3.2.4 on 2021-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='cash_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف نقدی'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='max_purchase',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='سقف خرید'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف درصدی'),
        ),
    ]
